# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LightroomDemoApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LightroomDemoApp
  platform :ios, "9.0"
  pod 'OpenCV', '2.4.9'
end